# Generated by Django 3.1.4 on 2020-12-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_price', to='product.product'),
        ),
    ]
